apiVersion: v1
kind: Pod
metadata:
  name: internal-kubectl
  namespace: kube-system
spec:
  serviceAccountName: internal-kubectl
  containers:
    - name: internal-kubectl
      image: Images:tag
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  internal-kubectl
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: internal-kubectl-role
  namespace: kube-system
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: internal-kubectl-rolebinding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: internal-kubectl # Name is case sensitive
roleRef:
  kind: Role
  name: internal-kubectl-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: internal-clusterrole
  namespace: kube-system
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrolebinding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: internal-kubectl
  namespace: kube-system # Name is case sensitive
roleRef:
  kind: ClusterRole
  name: internal-clusterrole
  apiGroup: rbac.authorization.k8s.io
